### ISSUE TITLE
Production Pivot file creates zones with 0's

### ISSUE THREAD

**Issue by jPeachPBA** [TransportScotland/tmfs18-trip-end-model#10]
Changing "create_production_pivot" to initialise the array with `np.ones` has caused issues for zones with zero population.
Will need to be changed to replace 0's with 1's at the end of the function to reflect the way that previous versions handled this.

**Comment by asongtoruin** [comment]
As discussed in emails, there is an issue in which when the model sees zero values, the growth is replaced with a 1. This means the TMfS14 files (mainly, `tmfs*.csv` I think) noticeably have ones for every zone at the airports and key ports. This will work in the main, though if a zone's population falls to 0 there may be a problem.

The following table shows what's happening:

                             | Zero in forecast   | Non-zero in   forecast
------------------- | ------------------- | -------------------
Zero in base         | Good                    | Underestimated¹
Non-zero in base | Underestimated²  | Good

¹ - Underestimated growth, because it’d be going from 1 to value rather than 0 to value, though there’s no clear way to calculate the latter
² - Underestimated reduction, because it’d be going from value to 1 rather than value to 0

**Comment by asongtoruin** [comment]
The above-referenced commit, in a branch called `zeroes` is an attempt to fully fix this (which requires the `tmfs*.csv` file for 2014 to have the ones replaced with zeroes). However, it doesn't quite work - see the results in [Check Zeroes.LOG](https://github.com/TransportScotland/tmfs18-trip-end-model/files/4648870/Check.Zeroes.LOG). For the time being, it's probably better to just apply a fix for the issue we're currently seeing, and leave this as a "known" edge case.

**Comment by asongtoruin** [comment]
Okay, it seems like these differences aren't actually caused by the commit I've done there, and instead are inherited from [this](https://github.com/TransportScotland/tmfs18-trip-end-model/commit/6c11fd3eb9b71b917023452c04c334cd74a88c48) commit, which gives the same results. There's something amiss here.

**Comment by jPeachPBA** [comment]
It looks like the issue is caused by this line is the problem - line 208 in `telmos_main.py` 

`sw_cte_array[j,:,8] = (cte_data[j,:,8] * 
                        production_growth[:,attr_growth_idxs[j]] * 
                        airport_growth)`

It should be using the `attraction_growth` array instead of `production_growth` for the final column
